### ISSUE TITLE
Sensor printing 0's

### ISSUE THREAD

**Issue by wightga** [pololu/vl53l1x-arduino#1]
When trying to run the continuous sketch or the other continuous sketch, the serial monitor just shows these being printed out.
⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮

The sensor works because it has printed out values on a different code from a different library and there must be something wrong with this one but I can't seem to find the issue.

**Comment by ruimarinho** [comment]
I think that’s a question of adjusting the baud rate of the serial monitor. 115k.

**Comment by wightga** [comment]
Yep, I literally just changed that right before I saw your answer and it worked. What exactly is the baud rate? and what does it do?

**Comment by ruimarinho** [comment]
It’s the number of bits per seconds transmitted by the communication channel. If it is incorrect, the monitor won’t be able to extract the information being sent.
