### ISSUE TITLE
about ROI

### ISSUE THREAD

**Issue by zhenyuan0530** [pololu/vl53l1x-arduino#11]
Sorry about that. I know this problem has discussed several times. but still remains unsolved.
I think that the best feature of this sensor is ROI. Because it can do more what i want to do.
So I really need this function. please help me. 
or anyone can teach me how to use "vl53l1x-st-api-arduino" on arduino uno board .

I really thank for you.

**Comment by kevin-pololu** [comment]
If you are having trouble working with our implementation of the API (vl53l1x-st-api-arduino), please post on the [Pololu forum](https://forum.pololu.com/) describing what you have tried and how your results differ from what you expect (including any error messages, if any).
