### ISSUE TITLE
Using another Wire than the default Wire (i2c)

### ISSUE THREAD

**Issue by cho934** [pololu/vl53l1x-arduino#13]
Hi,

The code doesn't seem to allow to change the Wire by Wire1 or Wire2.  Would it be possible de choose it in the constructor ?

BR,

**Comment by NB-CAD** [comment]
Did you ever get and answer or find a solution?

**Comment by kevin-pololu** [comment]
Sorry we took a while to address this. I just merged a pull request that adds a `setBus` function allowing you to choose a different `TwoWire` object. If you are still looking for this functionality, please try the latest version of the library.

Kevin

**Comment by NB-CAD** [comment]
Thank you Kevin. I was able to deal with this by changing ESP modules. Will revisit.
