### ISSUE TITLE
I don't work change address 

### ISSUE THREAD

**Issue by GianmarcoMicrotech** [pololu/vl53l1x-arduino#14]
Hi,
I have 4 VL53L1X sensor ( POLOLU board ), but i can't change the address the a VL53L1X sensor setting the register.If i use the default address the sensor response correctly. To avoid the problems i development a only sensor. Can you help me ? It's urgent ! Thanks you.

This my code:

#define AddressDefault		0x29

// Indirizzi 4 sensori di distanza
#define ADDRESS_VL1		0x29
#define ADDRESS_VL2		0x33
#define ADDRESS_VL3		0x35
#define ADDRESS_VL4		0x37 

bool			VL53L1X_init ( bool io_2v8 , uint8_t tmp_addr )
{
  // check model ID and module type registers (values specified in datasheet)
  if ( readReg16Bit ( IDENTIFICATION__MODEL_ID ) != 0xEACC )	
		return false ; 

  // VL53L1_software_reset() begin

  writeReg ( SOFT_RESET, 0x00 ) ;
  nrf_delay_ms ( 1 ) ;
  writeReg ( SOFT_RESET, 0x01 ) ;

  // give it some time to boot; otherwise the sensor NACKs during the readReg ( )
  // call below and the Arduino 101 doesn't seem to handle that well
	nrf_delay_ms ( 1 ) ;

  // VL53L1_poll_for_boot_completion() begin

  // startTimeout ( ) ;
	
  // check last_status in case we still get a NACK to try to deal with it correctly
  if ( ( readReg ( FIRMWARE__SYSTEM_STATUS ) & 0x01 ) == 0 )		
      return false ;	

  // VL53L1_poll_for_boot_completion() end

  // VL53L1_software_reset() end

  // VL53L1_DataInit() begin

  // sensor uses 1V8 mode for I/O by default; switch to 2V8 mode if necessary
  if ( io_2v8 )
  {
    writeReg ( PAD_I2C_HV__EXTSUP_CONFIG,
		readReg ( PAD_I2C_HV__EXTSUP_CONFIG ) | 0x01 ) ;
		
  }

	uint16_t fast_osc_frequency ;	
	
  // store oscillator info for later use
  fast_osc_frequency = readReg16Bit ( OSC_MEASURED__FAST_OSC__FREQUENCY ) ;
  // osc_calibrate_val = readReg16Bit ( RESULT__OSC_CALIBRATE_VAL ) ;

  // VL53L1_DataInit() end

  // VL53L1_StaticInit() begin

  // Note that the API does not actually apply the configuration settings below
  // when VL53L1_StaticInit() is called: it keeps a copy of the sensor's
  // register contents in memory and doesn't actually write them until a
  // measurement is started. Writing the configuration here means we don't have
  // to keep it all in memory and avoids a lot of redundant writes later.

  // the API sets the preset mode to LOWPOWER_AUTONOMOUS here:
  // VL53L1_set_preset_mode() begin

  // VL53L1_preset_mode_standard_ranging() begin

  // values labeled "tuning parm default" are from vl53l1_tuning_parm_defaults.h
  // (API uses these in VL53L1_init_tuning_parm_storage_struct ( ) )

  // static config
  // API resets PAD_I2C_HV__EXTSUP_CONFIG here, but maybe we don't want to do
  // that? (seems like it would disable 2V8 mode)
  writeReg16Bit ( DSS_CONFIG__TARGET_TOTAL_RATE_MCPS, TargetRate ) ; // should already be this value after reset
  writeReg ( GPIO__TIO_HV_STATUS, 0x02 ) ;
  writeReg ( SIGMA_ESTIMATOR__EFFECTIVE_PULSE_WIDTH_NS, 8 ) ; // tuning parm default
  writeReg ( SIGMA_ESTIMATOR__EFFECTIVE_AMBIENT_WIDTH_NS, 16 ) ; // tuning parm default
  writeReg ( ALGO__CROSSTALK_COMPENSATION_VALID_HEIGHT_MM, 0x01 ) ;
  writeReg ( ALGO__RANGE_IGNORE_VALID_HEIGHT_MM, 0xFF ) ;
  writeReg ( ALGO__RANGE_MIN_CLIP, 0 ) ; // tuning parm default
  writeReg ( ALGO__CONSISTENCY_CHECK__TOLERANCE, 2 ) ; // tuning parm default

  // general config
  writeReg16Bit ( SYSTEM__THRESH_RATE_HIGH, 0x0000 ) ;
  writeReg16Bit ( SYSTEM__THRESH_RATE_LOW, 0x0000 ) ;
  writeReg ( DSS_CONFIG__APERTURE_ATTENUATION, 0x38 ) ;

  // timing config
  // most of these settings will be determined later by distance and timing
  // budget configuration
  writeReg16Bit ( RANGE_CONFIG__SIGMA_THRESH, 360 ) ; // tuning parm default
  writeReg16Bit ( RANGE_CONFIG__MIN_COUNT_RATE_RTN_LIMIT_MCPS, 192 ) ; // tuning parm default

  // dynamic config

  writeReg ( SYSTEM__GROUPED_PARAMETER_HOLD_0, 0x01 ) ;
  writeReg ( SYSTEM__GROUPED_PARAMETER_HOLD_1, 0x01 ) ;
  writeReg ( SD_CONFIG__QUANTIFIER, 2 ) ; // tuning parm default

  // VL53L1_preset_mode_standard_ranging() end

  // from VL53L1_preset_mode_timed_ranging_*
  // GPH is 0 after reset, but writing GPH0 and GPH1 above seem to set GPH to 1,
  // and things don't seem to work if we don't set GPH back to 0 (which the API
  // does here).
  writeReg ( SYSTEM__GROUPED_PARAMETER_HOLD, 0x00 ) ;
  writeReg ( SYSTEM__SEED_CONFIG, 1 ) ; // tuning parm default

  // from VL53L1_config_low_power_auto_mode
  writeReg ( SYSTEM__SEQUENCE_CONFIG, 0x8B ) ; // VHV, PHASECAL, DSS1, RANGE
  writeReg16Bit ( DSS_CONFIG__MANUAL_EFFECTIVE_SPADS_SELECT, 200 << 8 ) ;
  writeReg ( DSS_CONFIG__ROI_MODE_CONTROL, 2 ) ; // REQUESTED_EFFFECTIVE_SPADS

  // VL53L1_set_preset_mode() end

  // default to long range, 50 ms timing budget
  // note that this is different than what the API defaults to
  setDistanceMode( Long ) ;
  // setMeasurementTimingBudget( 50000 ) ;

  // VL53L1_StaticInit() end

  // the API triggers this change in VL53L1_init_and_start_range() once a
  // measurement is started; assumes MM1 and MM2 are disabled
  writeReg16Bit ( ALGO__PART_TO_PART_RANGE_OFFSET_MM ,
	readReg16Bit ( MM_CONFIG__OUTER_OFFSET_MM ) * 4 ) ;
	
	nrf_delay_ms ( 100 ) ;
	
		// Setto il nuovo address
	setAddress ( tmp_addr ) ;
	
	// Utilizzare l'indirizzo del sensore che vado a leggere
	address = tmp_addr ;

	nrf_delay_ms ( 100 ) ;
	
	// check model ID and module type registers (values specified in datasheet)
  if ( readReg16Bit ( IDENTIFICATION__MODEL_ID ) != 0xEACC )	
		return false ; 
	
	startContinuous ( 100 ) ;

  return true ;
	
}
//////////////////////////////////////////////////////////////
// Setto il nuovo indirizzo
void			setAddress ( uint8_t new_addr )
{
	writeReg ( I2C_SLAVE__DEVICE_ADDRESS , new_addr & 0x7F ) ;
	
  address = new_addr ;
	
}

I understand that the address is not change because the sensor when i request the MODEL ID, after change the address, it not response.

Regards,

**Comment by kevin-pololu** [comment]
Hello,

It looks like this is the same as an issue that you posted about [on the Pololu forum](https://forum.pololu.com/t/i-dont-work-change-address-vl53l1x-sensor/18382), and it seems like you've resolved it now, but please continue the discussion on the forum if you have more questions.

Kevin
