### ISSUE TITLE
[bug] typo in code (in mostly occured bad range_status text mistake)

### ISSUE THREAD

**Issue by rejnok93** [pololu/vl53l1x-arduino#16]
There is mistake in function `VL53L1X::getRangingData()` when range_status is converted (line 684): `SignalFail` value is wrong! Please correct it to: `SigmaFail`
I looked into original ST API code of `ConvertStatusLite()` function in `vl53l1_api.c` file, there is the proof:
```
	case VL53L1_DEVICEERROR_MSRCNOTARGET:
		RangeStatus = VL53L1_RANGESTATUS_SIGNAL_FAIL;
		break;
	case VL53L1_DEVICEERROR_SIGMATHRESHOLDCHECK:
		RangeStatus = VL53L1_RANGESTATUS_SIGMA_FAIL;
```
The "SignalFail" and "SigmaFail" looks very similar, its only typo mistake, but it confused me very long time, before I accidetally found this typo. I thought that mostly occured fail in measuring is caused by something actually not true!

I created pull request: #17

**Comment by kevin-pololu** [comment]
Looks like you're right; I merged your pull request. Thanks!
